server:
  port: 8060
spring:
  application:
    name: INDICATOR
  data:
    mongodb:
      uri: mongodb+srv://greenimpact:123@cluster0.ovkx2sr.mongodb.net/?retryWrites=true&w=majority
      database: greenimpact
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9000/eureka
  instance:
    preferIpAddress: true